openapi: 3.0.2
servers: []
info:
  version: 2.0.0
  title: GA4GH Beacon API Specification - Analysis endpoints
  description: TBD
  contact:
    email: beacon@ga4gh.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /analyses:
    get:
      parameters:
        - $ref: '#/components/parameters/requestedSchema'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/includeResultsetResponses'
        - $ref: '#/components/parameters/filters'
      description: Get a list of bioinformatics analysis
      operationId: getAnalyses
      tags:
        - GET Endpoints
      responses:
        '200':
          $ref: '#/components/responses/ResultsOKResponse'
        default:
          $ref: https://progenetix.org/services/schemas/beaconErrorResponse.json
    post:
      description: Get a list of bioinformatics analysis
      operationId: postAnalysesRequest
      tags:
        - POST Endpoints
      requestBody:
        content:
          application/json:
            schema:
              $ref: https://progenetix.org/services/schemas/beaconRequestBody.json
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: https://progenetix.org/services/schemas/beaconResultsetsResponse.json
        default:
          description: An unsuccessful operation
          $ref: https://progenetix.org/services/schemas/beaconErrorResponse.json
  /analyses/{id}:
    parameters:
      - $ref: '#/components/parameters/entryId'
    get:
      description: Get details about one bioinformatics analysis, identified by its
        (unique) 'id'
      operationId: getOneAnalysis
      tags:
        - GET Endpoints
      responses:
        '200':
          $ref: '#/components/responses/ResultsOKResponse'
        default:
          description: An unsuccessful operation
          $ref: https://progenetix.org/services/schemas/beaconErrorResponse.json
    post:
      description: Get details about one bioinformatics analysis, identified by its
        (unique) 'id'
      operationId: postOneAnalysisRequest
      tags:
        - POST Endpoints
      requestBody:
        content:
          application/json:
            schema:
              $ref: https://progenetix.org/services/schemas/beaconRequestBody.json
        required: true
      responses:
        '200':
          $ref: '#/components/responses/ResultsOKResponse'
        default:
          description: An unsuccessful operation
          $ref: https://progenetix.org/services/schemas/beaconErrorResponse.json
  /analyses/{id}/g_variants:
    parameters:
      - $ref: '#/components/parameters/entryId'
    get:
      parameters:
        - $ref: '#/components/parameters/requestedSchema'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/limit'
      description: Get the list of variants instances for one bioinformatics analysis,
        identified by its (unique) 'id'
      operationId: getOneAnalysisVariants
      tags:
        - GET Endpoints
      responses:
        '200':
          $ref: '#/components/responses/ResultsOKResponse'
        default:
          description: An unsuccessful operation
          $ref: https://progenetix.org/services/schemas/beaconErrorResponse.json
    post:
      description: Get the list of variants instances for one bioinformatics analysis,
        identified by its (unique) 'id'
      operationId: postOneAnalysisVariantsRequest
      tags:
        - POST Endpoints
      requestBody:
        content:
          application/json:
            schema:
              $ref: https://progenetix.org/services/schemas/beaconRequestBody.json
        required: true
      responses:
        '200':
          $ref: '#/components/responses/ResultsOKResponse'
        default:
          description: An unsuccessful operation
          $ref: https://progenetix.org/services/schemas/beaconErrorResponse.json
components:
  responses:
    ResultsOKResponse:
      description: Successful operation.
      content:
        application/json:
          schema:
            oneOf:
              - $ref: https://progenetix.org/services/schemas/beaconBooleanResponse.json
              - $ref: https://progenetix.org/services/schemas/beaconCountResponse.json
              - $ref: https://progenetix.org/services/schemas/beaconResultsetsResponse.json
  parameters:
    requestedSchema:
      name: requestedSchema
      description: Schema to be used to format the `result` field in the response.
        The response will use Beacon format.
      in: query
      required: false
      schema:
        type: string
      example: ga4gh-service-info-v1.0
    skip:
      name: skip
      in: query
      schema:
        $ref: https://progenetix.org/services/schemas/beaconCommonComponents.json#/$defs/Skip
    limit:
      name: limit
      in: query
      schema:
        $ref: https://progenetix.org/services/schemas/beaconCommonComponents.json#/$defs/Limit
    includeResultsetResponses:
      $ref: https://progenetix.org/services/schemas/beaconCommonComponents.json#/$defs/IncludeResultsetResponses
    entryId:
      name: id
      in: path
      required: true
      schema:
        type: string
    filters:
      name: filters
      in: query
      schema:
        type: array
        items:
          type: string
        examples:
          -   - variantcaller:GATK4.0
