google_spreadsheet_tsv_url:
  base_url: https://docs.google.com/spreadsheets/d/e/2PACX-1vTtXHn655F6jBrvWX_qe5a__3wxGyDYXc5ozkWJnoicFfSsImLkUrMtFVIQaAdY-7Z5P5OIj6SH2o_o/pub
  params:
    output: tsv
    single: true
    gid: 0
skipped_columns:
  - SKIP
  - PROVENANCE_ID
  - LINK
  - SAMPLE_TYPES
