dataset:
  description: Information about the datasets available in the beacon instance
  request_entity_path_id: datasets
  id: dataset
  collection: Null
  response_schema: beaconCollectionsResponse
  bycon_response_class: BeaconDataResponse
  defaultSchema:
    id: dataset
    schema: https://progenetix.org/services/schemas/dataset/
  is_beacon_entity: true
  path_id_value_bycon_parameter: dataset_ids
  tests:
    - description: default test mode
      test_values:
        testMode: true


################################################################################

cohort:
  description: Information about the cohorts available in the beacon instance
  request_entity_path_id: cohorts
  id: cohort
  collection: collations
  response_schema: beaconCollectionsResponse
  bycon_response_class: BeaconDataResponse
  defaultSchema:
    id: cohort
    schema: https://progenetix.org/services/schemas/cohort/
  is_beacon_entity: true
  path_id_value_bycon_parameter: filters
  tests:
    - description: default test mode
      test_values:
        testMode: true


################################################################################

genomicVariant:
  description: >-
    Information about matching genomic variants from the corresponding dataset.
    The type of response used for the endpoint depends on the requested and granted
    `responseGranularity`.
  request_entity_path_id: g_variants
  request_entity_path_aliases:
    - genomicVariations
    - variants
  id: genomicVariant
  collection: variants
  response_schema: beaconResultsetsResponse
  bycon_response_class: BeaconDataResponse
  defaultSchema:
    id: genomicVariant
    schema: https://progenetix.org/services/schemas/genomicVariant/
  is_beacon_entity: true
  path_id_value_bycon_parameter: variant_ids
  tests:
    - description: default test mode
      test_values:
        testMode: true


################################################################################

analysis:
  description: >-
    Information about matching analyses from the corresponding dataset.
    The type of response used for the endpoint depends on the requested and granted
    `responseGranularity`.
  request_entity_path_id: analyses
  id: analysis
  collection: analyses  
  response_schema: beaconResultsetsResponse
  bycon_response_class: BeaconDataResponse
  defaultSchema:
    id: analysis
    schema: https://progenetix.org/services/schemas/analysis/
  is_beacon_entity: true
  path_id_value_bycon_parameter: analysis_ids
  tests:
    - description: default test mode
      test_values:
        testMode: true


##############################################################################

run:
  description: >-
    Information about matching experimental runs from the corresponding dataset.
    The type of response used for the endpoint depends on the requested and granted
    `responseGranularity`.
  request_entity_path_id: runs
  id: run
  collection: analyses  
  response_schema: beaconResultsetsResponse
  bycon_response_class: BeaconDataResponse
  defaultSchema:
    id: run
    schema: https://progenetix.org/services/schemas/run/
  is_beacon_entity: true
  path_id_value_bycon_parameter: run_ids
  tests:
    - description: default test mode
      test_values:
        testMode: true

################################################################################

biosample:
  description: >-
    Information about matching samples from the corresponding dataset.
    The type of response used for the endpoint depends on the requested and granted
    `responseGranularity`.
  request_entity_path_id: biosamples
  request_entity_path_aliases:
    - samples
  id: biosample
  collection: biosamples  
  response_schema: beaconResultsetsResponse
  bycon_response_class: BeaconDataResponse
  defaultSchema:
    id: biosample
    schema: https://progenetix.org/services/schemas/biosample/
  is_beacon_entity: true
  path_id_value_bycon_parameter: biosample_ids
  tests:
    - description: default test mode
      test_values:
        testMode: true


##############################################################################

individual:
  description: >-
    Information about matching subjects (individuals) from the corresponding dataset.
    The type of response used for the endpoint depends on the requested and granted
    `responseGranularity`.
  request_entity_path_id: individuals
  id: individual
  collection: individuals
  response_schema: beaconResultsetsResponse
  bycon_response_class: BeaconDataResponse
  defaultSchema:
    id: individual
    schema: https://progenetix.org/services/schemas/individual/
  is_beacon_entity: true
  path_id_value_bycon_parameter: individual_ids
  examples:
    - ?filters=EFO:0030049&limit=5
  tests:
    - description: default test mode
      test_values:
        testMode: true


############################################################################

phenopacket:
  description: >-
    Information about matching subjects (individuals) from the corresponding dataset,
    converted to Phenopackets format by aggregating the relevant information from
    the matched `individual`, `biosample`s, `analysis`(/es) and `genomicVariation`s.
  request_entity_path_id: phenopackets
  id: phenopacket
  collection: individuals
  response_schema: beaconResultsetsResponse
  bycon_response_class: BeaconDataResponse
  defaultSchema:
    id: phenopacket
    schema: https://progenetix.org/services/schemas/phenopacket/
  is_beacon_entity: true
  path_id_value_bycon_parameter: individual_ids
  tests:
    - description: default test mode
      test_values:
        testMode: true


################################################################################

filteringTerm:
  description: >-
    Information about the filtering terms available in the beacon instance.
  request_entity_path_id: filtering_terms
  id: filteringTerm
  collection: collations
  response_schema: beaconFilteringTermsResponse
  bycon_response_class: BeaconDataResponse
  defaultSchema:
    id: filteringTerm
    schema: https://progenetix.org/services/schemas/filteringTermsSchema/
  is_beacon_entity: true
  path_id_value_bycon_parameter: filters
  tests:
    - description: default test mode
      test_values:
        testMode: true


################################################################################

info:
  description: >-
    Information about the beacon instance.
  request_entity_path_id: info
  request_entity_path_aliases:
    - "/"
    - "service-info"
    - "service_info"
  id: info
  response_schema: beaconInfoResponse
  bycon_response_class: BeaconInfoResponse
  defaultSchema:
    id: configuration
    schema: https://progenetix.org/services/schemas/beaconInfoResults/
  is_beacon_entity: true
  content: {}


################################################################################

beaconMap:
  description: >-
    Map of the beacon instance configuration.
  request_entity_path_id: map
  id: beaconMap
  collection: Null
  response_schema: beaconMapResponse
  bycon_response_class: BeaconInfoResponse
  defaultSchema:
    id: map
    schema: https://progenetix.org/services/schemas/beaconMapSchema/
  is_beacon_entity: true


################################################################################

configuration:
  description: >-
    Information about the beacon instance configuration.
  request_entity_path_id: configuration
  id: configuration
  collection: Null
  response_schema: beaconConfigurationResponse
  bycon_response_class: BeaconInfoResponse
  defaultSchema:
    id: configuration
    schema: https://progenetix.org/services/schemas/beaconConfigurationSchema/
  is_beacon_entity: true


################################################################################

entryType:
  request_entity_path_id: entry_types
  id: entryType
  collection: Null
  response_schema: beaconEntryTypesResponse
  bycon_response_class: BeaconInfoResponse
  defaultSchema:
    id: entryType
    schema: https://progenetix.org/services/schemas/entryTypesSchema/
  is_beacon_entity: true

