"$schema": https://json-schema.org/draft/2020-12/schema
"$id": https://progenetix.org/services/schemas/Biosample/v2021-03-05
title: Biosample
meta:
  contributors:
    - description: "GA4GH Metadata Task Team"
    - description: "Michael Baudis"
      id: "orcid:0000-0002-9903-4248"
    - description: "Jules Jacobsen"
      id: "orcid:0000-0002-3265-15918"
    - description: "Peter Robinson"
      id: "orcid:0000-0002-0736-91998"
  provenance:
    - description: "Developer branch of original GA4GH schema"
      id: 'https://github.com/ga4gh-metadata/metadata-schemas/blob/master/schemas/biometadata.proto#L84'
    - description: "Phenopackets"
      id: 'https://github.com/phenopackets/phenopacket-schema/blob/master/docs/biosample.rst'
    - description: "Progenetix `bycon` project"
      id: 'https://github.com/progenetix/bycon/'
  used_by:
    - description: "Progenetix database schema (Beacon+ backend)"
      id: 'https://github.com/progenetix/schemas/'
  sb_status: community
description: >
  A Biosample refers to a unit of biological material from which the substrate
  molecules (e.g. genomic DNA, RNA, proteins) for molecular analyses (e.g.
  sequencing, array hybridisation, mass-spectrometry) are extracted. Examples
  would be a tissue biopsy, a single cell from a culture for single cell genome
  sequencing or a protein fraction from a gradient centrifugation. Several
  instances (e.g. technical replicates) or types of experiments (e.g.
  genomic array as well as RNA-seq experiments) may refer to the same Biosample.
required:
  - id
  - biocharacteristics
  - externalReferences
properties:
  id:
    type: string
    examples:
      - pgxbs-kftvjtgm
  individualId:
    type: string
    examples:
      - pgxind-kftx5ruq
  description:
    type: string
    examples:
      - breast carcinoma
      - adenocarcinoma [cell line HeLa]
  biocharacteristics:
    type: array
    items:
      "$ref": OntologyClass.yaml#/properties
    examples:
      - id: NCIT:C4029
        label: Cervical Adenocarcinoma
      - id: UBERON:0000002
        label: uterine cervix
  externalReferences:
    type: array
    items:
      "$ref": OntologyClass.yaml#/properties
    examples:
      - id: PMID:9892199
  cohorts:
    description: >
      Cohorts describe collections of samples or individuals which are part of a common epistemic group, e.g. have been used for a study or share a set of features.
    type: array
    items:
      "$ref": OntologyClass.yaml#/properties
    examples:
      - id: pgxcohort-arraymap
        label: arrayMap collection
  individualAgeAtCollection:
    "$ref": Age.yaml#/properties
  provenance:
    "$ref": Provenance.yaml#/properties
  dataUseConditions:
    "$ref": OntologyClass.yaml#/properties
  sampledTissue:
    "$ref": OntologyClass.yaml#/properties
  histologicalDiagnosis:
    "$ref": OntologyClass.yaml#/properties
  info:
    type: object
  updated:
    type: string
    format: date-time
    examples:
      - "2020-09-10T17:44:10.170Z"
